### ISSUE TITLE
Navbar doesn't display on Smartphone screens

### ISSUE THREAD

**Issue by Tusharbansa1** [saloni-garg/ECell-Website#11]
site responsiveness changes in phone , want to work on it

**Comment by saloni-garg** [comment]
Yes. Actually Navbar is not showing on XS screens. I'm working on it, would be great to see you work and send some useful PRs :)

**Comment by Tusharbansa1** [comment]
created a pr . please have a look on it , needless to say but after merging u can test it opening in crome , press ctrl+shift+i and then ctrl+shift+m , ,, #12

**Comment by hedelaerke** [comment]
Hi! It looks like menu items disappear after screen gets 766px wide in general. 
I found out that the reason why your menu items don't display is this part of  your CSS 
".collapse {
display: none}"

**Comment by darshana-buddhika** [comment]
hi i can help you with fixing this
