### ISSUE TITLE
Make the Contact Us Form working

### ISSUE THREAD

**Issue by saloni-garg** [saloni-garg/ECell-Website#7]
The **'Contact Us'** form **_(http://ecell.lnmiit.ac.in)_** is not working. Find the issues and correct them.

**Comment by dinukadesilva** [comment]
I'l work on this

**Comment by dinukadesilva** [comment]
@saloni-garg  Could you explain me what's not working

**Comment by saloni-garg** [comment]
Open the website here http://ecell.lnmiit.ac.in 
In the navbar, you'll see the last option is Contact Us, click there and you'll be scrolled down in the Contact Us form, it accepts input but doesn't send the mails on the E-Mail address mentioned.

**Comment by bhatiatanish** [comment]
@saloni-garg I made a fix. hope its working now. please close the issue if it does.
